services:
  forensync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forensync_app
    ports:
      - "5000:5000"
    volumes:
      - ./evidence:/app/evidence
      - ./reports:/app/reports
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
